apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: database
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_USER: "smartdb_user"
  POSTGRES_PASSWORD: "SecurePassw0rd2024!"
  POSTGRES_DB: "smartdb"
